# This is an example config provided with the orchestrator and can be overwritten with
# environment variable `ORCHESTRATOR_CONFIG` pointing to a configuration file path
# at application deploy time.

# Generation server that will be used on any orchestrator endpoints requiring generation
generation:
    # The `provider` refers to the specific generation API to be used, currently text generation:
    # - `tgis` refers to the [TGIS generation API](https://github.com/IBM/text-generation-inference/blob/main/proto/generation.proto)
    # - `nlp` refers to the [caikit-nlp API](https://github.com/caikit/caikit-nlp/tree/main/caikit_nlp/modules/text_generation)
    provider: tgis # tgis or nlp
    service:
        hostname: localhost
        port: 8033
# Generation server used for chat endpoints
# chat_generation:
#   service:
#     hostname: localhost
#     port: 8080
#   # health_service:
# Any chunker servers that will be used by any detectors
chunkers:
    # Chunker ID/name
    en_regex:
        type: sentence
        service:
            hostname: localhost
            port: 8085
            # TLS ID/name, optional (detailed in `tls` section)
            tls: caikit
# Any detector servers that will be used by an application to provide detections.
# Users will refer to detectors by ID/name in their requests
detectors:
    # Detector ID/name to be used in user requests
    hap-en:
        # Detector type (text_contents, text_generation, text_chat, text_context_doc)
        type: text_contents
        service:
            hostname: localhost
            port: 8080
            # TLS ID/name, optional (detailed in `tls` section)
            tls: detector
        health_service:
            hostname: localhost
            port: 8081
        # Chunker ID/name from `chunkers` section if applicable
        chunker_id: en_regex
        # Default score threshold for a detector. If a user
        # request does not provide threshold, this will be used to filter
        # out detector results by score below this threshold
        default_threshold: 0.5
# For flexibility for use across multiple servers (e.g. multiple detector servers),
# TLS configuration information can be referred to by name.
tls:
    # Chosen ID/name for particular TLS config
    caikit:
        cert_path: /path/to/tls.crt
        key_path: /path/to/tls.key
        client_ca_cert_path: /path/to/ca.crt
    detector:
        cert_path: /path/to/tls.crt
        key_path: /path/to/tls.key
        client_ca_cert_path: /path/to/ca.crt
        insecure: false
    detector_bundle_no_ca:
        cert_path: /path/to/client-bundle.pem
        insecure: true
# Following section can be used to configure the allowed headers that orchestrator will pass to
# NLP provider and detectors. Note that, this section takes header keys, not values.
# passthrough_headers:
#     - header-key
