generation:
    provider: tgis # tgis or nlp
    service:
        hostname: localhost
        port: 8033
chunkers:
    en_regex:
        type: sentence
        service:
            hostname: localhost
            port: 8085
            tls: caikit
detectors:
    hap-en:
        service:
            hostname: https://localhost/api/v1/detector
            port: 8080
            tls: caikit
        chunker_id: en_regex
        config:
            default_threshold: 0.5
tls:
    caikit:
        cert_path: /path/to/tls.crt
        key_path: /path/to/tls.key
        client_ca_cert_path: /path/to/ca.crt
